### ISSUE TITLE
Mismatch on diagrams and code.

### ISSUE THREAD

**Issue by rwestwick** [modmypi/MCP23017_HAT#1]
The diagram for led.py in the 3. Example Code Wiring Diagrams page (https://github.com/modmypi/MCP23017_HAT/wiki/3.-Example-Code-Wiring-Diagrams) shows the wires connected to IC1. The led.py code shows connected ic as IC2!

# define the i2c address of ic1, this is set by the jumpers on the HAT
ic1_i2c_addr = 0x24

As an example this code/diagram made me think that new board was not working. This needs to be changed.

**Comment by modmypi** [comment]
The new MCP23017 HAT's have different default addresses:

IC1 is, by default, addressed as 0x24
IC2 is, by default, addressed as 0x20

The code was updated to reflect the new default addresses.

If your HAT looks like the one pictured in the examples - https://github.com/modmypi/MCP23017_HAT/wiki/3.-Example-Code-Wiring-Diagrams - then this is an old version of the board where the addresses are switched, IC1 = 0x20 and IC2 = 0x24.

If your HAT looks like the one pictured on our product page - https://www.modmypi.com/raspberry-pi/iousbanalogue-expansion-1028/gpio-expansion-boards-1029/modmypi-mcp23017-hat-32-channel-io-expansion-hat/ - Then these are correctly addressed.
